perfsee/perfsee

.github/workflows/rebase.yaml
README.md

allow fast rebase with `/rebase` command in comment

ci: setup auto rebase workflow

---

packages/platform/src/icons.tsx
packages/platform/src/modules/project/settings/settings-environments/form-cookies.tsx

feat(platform): environment settings

---

packages/dls/src/variables.ts

feat(dls): update default font family

---

packages/platform/src/modules/snapshots/components/snapshot-detail-content/pivot-content-asset/asset-transferred.tsx
packages/platform/src/modules/snapshots/components/snapshot-detail-content/pivot-content-asset/columns.tsx
packages/platform/src/modules/snapshots/snapshot-type.ts

fix(platform): color map of request type

---

packages/platform/src/modules/project/statistics/artifact-size.tsx
packages/platform/src/modules/project/statistics/index.tsx
packages/platform/src/modules/project/statistics/module.ts
packages/platform/src/modules/project/statistics/snapshot-metrics.tsx
packages/platform/src/modules/version-report/index.tsx
packages/platform/src/modules/version-report/types.ts
packages/platform/src/modules/version-report/version-report.module.ts

feat(platform): project homepage should start with loading

---

packages/platform-server/src/modules/github/resolver.ts
packages/platform-server/src/modules/github/service.ts
packages/platform/src/modules/import-github/associated-github-installations.module.tsx
packages/platform/src/modules/import-github/github-installation.module.ts
packages/platform/src/modules/import-github/installation-selector.tsx
packages/platform/src/modules/import-github/style.ts
packages/schema/src/graphql/github/associated-github-installations.gql
packages/schema/src/graphql/github/github-installation.gql
packages/schema/src/server-schema.gql

Choose account:
When user has not installed our github application:
When user has not connected with github account:

feat(platform): clearer github account selection

---

packages/platform/src/modules/components/bundle-property/branch-selector.tsx
packages/platform/src/modules/project/statistics/artifact-size.tsx
packages/platform/src/modules/project/statistics/module.ts
packages/platform/src/modules/project/statistics/snapshot-metrics.tsx
packages/platform/src/modules/shared/property.module.ts
packages/platform/src/modules/version-report/version-report.module.ts

Still have some twinkle between loading and empty state.

fix: homepage loading twinkle

---

packages/components/src/color-button/index.tsx
packages/components/src/index.ts
packages/components/src/modal/index.tsx
packages/components/src/modal/style.tsx
packages/platform-server/src/modules/permission/__tests__/provider.spec.serial.ts
packages/platform-server/src/modules/permission/providers/none.ts
packages/platform-server/src/modules/permission/providers/self-host/index.ts
packages/platform-server/src/modules/project/__tests__/project.service.spec.serial.ts
packages/platform-server/src/modules/project/__tests__/project.spec.e2e.ts
packages/platform-server/src/modules/project/resolver.ts
packages/platform-server/src/modules/project/service.ts
packages/platform-server/src/modules/project/types.ts
packages/platform-server/src/modules/snapshot/__tests__/service.spec.e2e.ts
packages/platform-server/src/modules/snapshot/resolver.ts
packages/platform/src/modules/lab/operator-comps/create-snapshot.tsx
packages/platform/src/modules/layout/nav-items.ts
packages/platform/src/modules/layout/project-nav.tsx
packages/platform/src/modules/project/features.tsx
packages/platform/src/modules/project/settings/settings-basic/danger-zone.tsx
packages/platform/src/modules/project/settings/settings-basic/style.tsx
packages/schema/src/graphql/project/fragments/project-fields.gql
packages/schema/src/server-schema.gql
packages/shared/src/utils/permission.ts

feat(platform,platform-server): make project public to anyone

---

packages/runner/lab/package.json
yarn.lock

https://github.com/perfsee/perfsee/security/dependabot/13

chore: upgrade vm2 to 3.9.11

---

packages/platform/src/modules/bundle/detail/index.tsx
packages/platform/src/modules/components/artifact-select/index.tsx
packages/platform/src/modules/components/artifact-select/module.ts
packages/platform/src/modules/components/artifact-select/style.tsx

feat(platform): artifact selector name filter

---

.github/renovate.json

chore: renovate linter preset did not work well

---

packages/runner/lab/src/lighthouse/lighthouse-runtime/gatherers/console-logger.ts
packages/runner/lab/src/lighthouse/lighthouse-runtime/gatherers/index.ts
packages/runner/lab/src/lighthouse/lighthouse-runtime/index.ts
types/lighthouse/index.d.ts

log out page console for debug

feat(job-runner-lab): lab console logger

---

packages/platform/src/modules/project/settings/settings-environments/form-cookies.tsx
packages/shared/src/types/snapshot.ts

feat(platform): add same site attribute for cookie

---

packages/components/src/index.ts
packages/components/src/pop-confirm/index.tsx
packages/components/src/pop-confirm/style.tsx
packages/platform-server/src/modules/notification/__tests__/service.spec.serial.ts
packages/platform-server/src/modules/notification/service.ts
packages/platform-server/src/modules/project/__tests__/project.service.spec.serial.ts
packages/platform-server/src/modules/project/__tests__/project.spec.e2e.ts
packages/platform-server/src/modules/project/resolver.ts
packages/platform-server/src/modules/project/service.ts
packages/platform-server/src/modules/project/types.ts
packages/platform/src/modules/components/user-input/user-emails-input.tsx
packages/platform/src/modules/project/settings/index.tsx
packages/platform/src/modules/project/settings/settings-basic/basic-info.tsx
packages/platform/src/modules/project/settings/settings-basic/module.ts
packages/platform/src/modules/project/settings/settings-permission/index.tsx
packages/platform/src/modules/project/settings/settings-permission/module.ts
packages/platform/src/modules/project/settings/settings-permission/styled.tsx
packages/schema/src/graphql/project/fragments/project-fields.gql
packages/schema/src/graphql/project/project-authed-users.gql
packages/schema/src/graphql/project/update-project-user-permission.gql
packages/schema/src/server-schema.gql

feat(platform,platform-server): allow project to add read permission users

---

packages/components/src/donut-chart/index.tsx

fix(components): fix donut chart style

---

packages/plugins/esbuild/src/adaptor.ts
packages/plugins/rollup/src/adaptor.ts
packages/plugins/rollup/src/index.ts
packages/plugins/utils/src/build-env.ts
packages/plugins/utils/src/build-upload-client.ts
packages/plugins/utils/src/options.ts
packages/plugins/utils/src/reports.ts
packages/plugins/webpack/src/index.ts

fix(plugin-utils): avoid plugin crashing if no git env found

---

packages/platform-server/src/db/fixtures/seed.ts
packages/platform-server/src/db/mysql/property.entity.ts
packages/platform-server/src/modules/snapshot/__tests__/service.spec.serial.ts
packages/platform-server/src/modules/snapshot/service.ts
packages/platform-server/src/modules/snapshot/snapshot-report/service.ts
packages/platform/src/modules/competitor/competitor.tsx
packages/platform/src/modules/lab/operator-comps/existed-pages.tsx
packages/platform/src/modules/lab/operator-comps/temp-pages.tsx
packages/platform/src/modules/project/settings/settings-environments/env-edit-form.tsx
packages/platform/src/modules/project/settings/settings-environments/index.tsx
packages/platform/src/modules/project/settings/settings-pages/competitor-page-edit-form.tsx
packages/platform/src/modules/project/settings/settings-pages/index.tsx
packages/platform/src/modules/project/settings/settings-pages/page-edit-form.tsx
packages/platform/src/modules/project/settings/settings-schedule/property-selectors.tsx
packages/platform/src/modules/project/statistics/charts/snapshot-metrics/chart.tsx
packages/platform/src/modules/project/statistics/snapshot-metrics.tsx
packages/schema/src/server-schema.gql

feat(platform-server): deprecate isCompetitor of environment

---

packages/flamechart/README.md
packages/flamechart/src/components/flamechart-container.tsx
packages/flamechart/src/components/flamechart-group-container.tsx
packages/flamechart/src/components/flamechart-view-container.tsx
packages/flamechart/src/themes/dark-theme.ts
packages/flamechart/src/themes/light-theme.ts
packages/flamechart/src/themes/theme.ts
packages/flamechart/src/views/flamechart-binding-manager.ts
packages/flamechart/src/views/flamechart-view-controller.ts
packages/flamechart/src/views/flamechart-view-renderer.ts

https://user-images.githubusercontent.com/13579374/203915755-5b2df2e6-6d44-4e81-a0f9-9c853463bff2.mov

feat(flamechart): timeline cursor

---

packages/bundle-analyzer/package.json
packages/bundle-analyzer/src/__tests__/analyzer.spec.ts
packages/bundle-analyzer/src/bundle-extractor.ts
packages/bundle-analyzer/src/stats-parser/index.ts
packages/plugins/utils/package.json
packages/plugins/utils/src/build-upload-client.ts
packages/plugins/utils/src/options.ts
packages/runner/bundle/src/bundle/index.ts
packages/runner/source/src/source/index.ts
yarn.lock

Changes:
https://github.com/msgpack/msgpack-javascript/compare/main...EYHN:msgpack-javascript:feat/async-stream
Serialization and deserialization take about two times longer, but save a lot of memory and can handle data larger than 4gb.

feat(plugins, bundle-analyzer): stream serialize

---

packages/platform-server/src/modules/job/service.ts
packages/platform-server/src/modules/runner/service.ts

feat(platform-server): auto add job available zone if new runner registered

---

packages/platform-server/src/modules/artifact/resolver.ts
packages/platform-server/src/modules/artifact/service.ts
packages/platform-server/src/modules/job/service.ts
packages/platform-server/src/modules/notification/service.ts
packages/platform-server/src/modules/project/service.ts
packages/platform-server/src/modules/runner/resolver.ts
packages/platform-server/src/modules/setting/__tests__/setting.service.spec.serial.ts
packages/platform-server/src/modules/setting/resolver.ts
packages/platform-server/src/modules/setting/service.ts
packages/platform-server/src/modules/snapshot/service.ts
packages/platform-server/src/modules/source/service.ts
packages/platform-server/src/utils/data-loader.ts
packages/platform/src/modules/project/statistics/artifact-size.tsx
packages/schema/src/server-schema.gql

fix(platform-server): correct dataloader return type

---

packages/platform-server/src/modules/environment/__tests__/service.spec.serial.ts
packages/platform-server/src/modules/environment/index.ts
packages/platform-server/src/modules/environment/service.ts
packages/platform-server/src/modules/page/__tests__/service.spec.e2e.ts
packages/platform-server/src/modules/page/__tests__/service.spec.serial.ts
packages/platform-server/src/modules/page/index.ts
packages/platform-server/src/modules/page/service.ts
packages/platform-server/src/modules/profile/__tests__/service.spec.serial.ts
packages/platform-server/src/modules/profile/index.ts
packages/platform-server/src/modules/profile/service.ts
packages/platform-server/src/modules/snapshot/service.ts
packages/platform-server/src/modules/snapshot/snapshot-report/index.ts
packages/platform-server/src/modules/snapshot/snapshot-report/resolver.ts
packages/platform-server/src/modules/snapshot/snapshot-report/service.ts
packages/schema/src/server-schema.gql

fix(platform-server): delete relevant files in storage when property is deleted

---

packages/bundle-report/src/bundle-detail/resource-tabs/audits.tsx
packages/components/src/audit-item/index.tsx
packages/platform/src/modules/snapshots/components/snapshot-detail-content/pivot-content-performance/index.tsx

feat(platform): show scores in audits detail

---

db/migrations/1673235793300-appversion-associate.ts
packages/bundle-report/src/bundle-detail/build-history.tsx
packages/bundle-report/src/bundle-detail/types.ts
packages/platform-server/src/db/mysql/app-version.entity.ts
packages/platform-server/src/db/mysql/artifact.entity.ts
packages/platform-server/src/modules/app-version/resolver.ts
packages/platform-server/src/modules/app-version/service.ts
packages/platform-server/src/modules/artifact/__tests__/service.spec.serial.ts
packages/platform-server/src/modules/artifact/controller.ts
packages/platform-server/src/modules/artifact/resolver.ts
packages/platform-server/src/modules/artifact/service.ts
packages/platform-server/src/modules/snapshot/service.ts
packages/platform/src/icons.tsx
packages/platform/src/modules/bundle/list/index.tsx
packages/platform/src/modules/bundle/list/style.ts
packages/platform/src/modules/components/artifact-select/index.tsx
packages/platform/src/modules/components/commit/app-version.module.ts
packages/platform/src/modules/components/commit/index.tsx
packages/platform/src/modules/components/commit/tooltip.tsx
packages/platform/src/modules/components/commit/use-app-version.ts
packages/platform/src/modules/lab/list/snapshot-meta.tsx
packages/plugins/utils/src/build-upload-client.ts
packages/schema/src/graphql/bundle/artifacts.gql
packages/schema/src/graphql/bundle/fragments/artifact.gql
packages/schema/src/graphql/project/app-version-by-hash.gql
packages/schema/src/server-schema.gql
packages/shared/src/utils/codebase.ts
packages/utils/src/git/host.ts

feat(platform,platform-server): show commit message

---

packages/platform-server/src/modules/snapshot/service.ts

fix(platform-server): try to complete the snapshot when all reports are completed

---

packages/platform/src/modules/admin/runners/module.ts

feat(platform): only show online runners by default

---

packages/platform/src/modules/project/list.tsx

fix(platform): cast possible numeric query value to string

---

packages/bundle-report/src/bundle-detail/resource-tabs/packages-table.tsx
packages/bundle-report/src/bundle-detail/style.ts

fix(platform): optimize the interaction of bundle packages

---

docker-compose.yml

move image build phase to prepare service

---

docs/docs/bundle/plugin-options.md
docs/i18n/cn/docusaurus-plugin-content-docs/current/bundle/plugin-options.md
packages/plugins/utils/src/build-upload-client.ts
packages/plugins/utils/src/options.ts

fix: add options to specify platform by plugin options

---

packages/schema/src/graphql/webhook/events/bundle-finished.gql

fix: add baseline on webhook

---

packages/platform/src/modules/webhook/index.tsx

feat(platform): webhook show last delivery time

---

packages/platform-server/src/__tests__/graphql.spec.e2e.ts
packages/platform-server/src/db/fixtures/project.ts
packages/platform-server/src/modules/application/__tests__/application.spec.e2e.ts
packages/platform-server/src/modules/file/file.controller.ts
packages/platform-server/src/modules/file/index.ts
packages/platform-server/src/modules/permission/guard.ts
packages/platform-server/src/modules/permission/providers/self-host/index.ts
packages/platform-server/src/modules/project/__tests__/project.service.spec.serial.ts
packages/platform-server/src/modules/project/__tests__/project.spec.e2e.ts
packages/platform-server/src/modules/project/resolver.ts
packages/platform-server/src/modules/project/service.ts
packages/platform/src/modules/shared/project.module.ts

patch project accessing behavior of unsigned users

---

Dockerfile

Correction base image

---

packages/bundle-analyzer/src/stats-parser/index.ts

fix(bundle-analyzer): missing module path

---

packages/bundle-report/src/bundle-detail/components/colored-size.tsx
packages/bundle-report/src/bundle-detail/components/diff.tsx
packages/bundle-report/src/bundle-detail/components/transfer-time.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/assets-table-row.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/assets-table.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/package-table-row.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/packages-table.tsx
packages/bundle-report/src/bundle-detail/style.ts

fix(platform): the interaction of bundle report

---

packages/plugins/rollup/src/adaptor.ts

fix: assets with vite

---

docs/docs/bundle/plugin-options.md
docs/i18n/cn/docusaurus-plugin-content-docs/current/bundle/plugin-options.md
packages/bundle-report/src/static.tsx
packages/plugins/esbuild/README.md
packages/plugins/rollup/README.md
packages/plugins/utils/package.json
packages/plugins/utils/src/options.ts
packages/plugins/utils/src/reports.ts
packages/plugins/utils/src/viewer.ts
packages/plugins/webpack/README.md
tools/cli.js
tools/cli/bundle.ts
tools/webpack/frontend-config.ts
yarn.lock

feat(plugin-utils): plugin output static report

---

packages/platform-server/src/modules/snapshot/resolver.ts
packages/platform-server/src/modules/snapshot/service.ts
packages/platform/src/modules/group/home/group-table-row.tsx
packages/platform/src/modules/group/home/group-table.tsx
packages/platform/src/modules/group/home/metric-diff.tsx
packages/platform/src/modules/group/home/module.ts
packages/platform/src/modules/project/list.module.ts
packages/platform/src/modules/project/list.tsx
packages/schema/src/graphql/group/snapshot-reports.gql
packages/schema/src/server-schema.gql

fix(platform): group detail

---

packages/platform/src/modules/components/artifact-select/index.tsx
packages/platform/src/modules/components/artifact-select/module.ts

fix(platform): allow filtering artifacts in baseline selection view

---

docs/docs/settings/basic-setting.md
docs/i18n/cn/docusaurus-plugin-content-docs/current/settings/basic-setting.md
packages/platform-server/src/modules/notification/shared.ts
packages/platform/src/modules/project/settings/settings-basic/notification.tsx
packages/shared/src/utils/index.ts
packages/shared/src/utils/is-wildcard-match.ts

feat(platform-server): allow filtering bundle notification branch by wildcards

---

packages/plugins/esbuild/src/util.ts

fix(esbuild): fix esbuild find path match

---

packages/runner/lab/src/lighthouse/helpers/react.ts

should get last 2 or 3 dependencies from the decl statement

fix(job-runner-lab): fix react profiling getting deps

---

packages/package/src/analyzer.ts
packages/platform-server/src/db/mysql/package.entity.ts
packages/platform-server/src/modules/package/resolver.ts
packages/platform/src/modules/package/detail/pivot-content-overview/index.tsx
packages/schema/src/server-schema.gql

1. fix self deps lost
2. increase placeholder length
3. fix styles
4. fix package projectId by slug on gql

fix(platform): fix package analysis issues

---

packages/flamechart/src/lib/react-devtool/deserializer.ts
packages/flamechart/src/lib/react-devtool/index.ts
packages/flamechart/src/lib/react-devtool/react-profile.ts
packages/flamechart/src/lib/react-devtool/react-timeline.ts
packages/flamechart/src/lib/react-devtool/replayer.ts
packages/flamechart/src/lib/react-devtool/types.ts
packages/ori/index.d.ts
packages/ori/src/lib.rs
packages/ori/src/parser.rs
packages/platform-server/src/modules/source/service.ts
packages/platform/src/modules/snapshots/components/snapshot-detail-content/pivot-content-flamechart/flamechart.tsx
packages/runner/lab/src/lighthouse/helpers/react.ts
packages/runner/lab/src/lighthouse/lighthouse-runtime/gatherers/devtools-injection.ts
packages/runner/lab/src/lighthouse/lighthouse-runtime/gatherers/react-profiler.ts
packages/runner/lab/src/lighthouse/lighthouse-worker.ts
packages/runner/source/src/source/index.ts
packages/server-common/src/types/index.ts
tools/cli/generate-react.ts

Support react flamechart sourcemap analyzsis.

feat: react sourcemap analysis

---

packages/plugins/utils/src/build-upload-client.ts
packages/plugins/utils/src/options.ts
packages/plugins/utils/src/reports.ts

to support users to view bundle results in custom dimensions

feat(plugin-utils): support custom processing stats file

---

packages/platform-server/src/modules/job/service.ts

```ts
async jobDone(id: number, duration: number, errored?: boolean, pendingLogs?: JobLog[]) {
// ...
if (job) {
// ...
if (errored) {
this.metrics.jobFail(1, { jobType: job.jobType })
} else {
this.metrics.jobSuccess(1, { jobType: job.jobType })
}
}
}
```

fix(platform): fix job fail metrics logic

---

packages/platform-server/src/modules/package/service.ts

Admins can see all packages now.

feat(platform-server): admin can see all packages

---

packages/runner/lab/src/lighthouse/helpers/react.ts

To fix this situation: react-dom 18.3.0-canary-xxx is released before 18.3.0

fix(job-runner): fix fetching react script

---

packages/flamechart/src/components/flamechart-group-container.tsx
packages/flamechart/src/components/flamechart-view-container.tsx
packages/flamechart/src/components/tooltip/calltreenode-tooltip.tsx
packages/flamechart/src/components/tooltip/perfsee-flamechart-tooltip.tsx
packages/flamechart/src/components/tooltip/timing-tooltip.tsx
packages/flamechart/src/index.ts
packages/flamechart/src/lib/canvas-2d-batch-renderers.ts
packages/flamechart/src/lib/flamechart-image.ts
packages/flamechart/src/lib/profile-search.ts
packages/flamechart/src/lib/profile.ts
packages/flamechart/src/lib/text-utils.ts
packages/flamechart/src/lib/tracehouse-profile.ts
packages/flamechart/src/views/flamechart-view-controller.ts
packages/flamechart/src/views/flamechart-view-renderer.ts
packages/flamechart/src/views/flamechart-view.ts
packages/platform/src/modules/snapshots/components/snapshot-detail-content/pivot-content-flamechart/flamechart.tsx

feat(flamechart): label image

---

packages/platform-server/src/modules/artifact/service.ts
packages/platform/src/modules/bundle/list/index.tsx

feat(platform): artifact list search

---

packages/flamechart/src/components/flamechart-container.tsx
packages/flamechart/src/components/flamechart-factory.ts
packages/flamechart/src/lib/non-stack-profile.ts
packages/flamechart/src/lib/profile.ts
packages/flamechart/src/lib/utils.ts
packages/package-report/src/pivot-content-benchmark/index.tsx

remove left heavy flamechart factory, use getLeftHeavyProfile

refactor(flamechart): remove left heavy flamechart factory

---

packages/platform/src/modules/bundle/detail/index.tsx
packages/platform/src/modules/bundle/detail/module.ts

like: `http://localhost:8080/projects/perfsee/bundle/8?baseline=18`

feat(platform): add bundle baseline on url

---

packages/platform/src/modules/project/settings/settings-environments/index.tsx
packages/platform/src/modules/project/settings/settings-pages/page-list-cell.tsx
packages/platform/src/modules/project/settings/settings-pages/style.tsx
packages/platform/src/modules/project/settings/settings-profiles/index.tsx
packages/platform/src/modules/project/settings/style.ts

feat(platform): show property ids

---

packages/lab-report/src/context.ts

Revert "fix(lab-report): fix lab use queryString"

---

packages/platform/src/icons.tsx
packages/platform/src/modules/project/settings/settings-common-comp.tsx
packages/platform/src/modules/project/settings/settings-environments/env-edit-form.tsx
packages/platform/src/modules/project/settings/settings-environments/form-cookies.tsx
packages/platform/src/modules/project/settings/settings-environments/form-headers.tsx
packages/platform/src/modules/project/settings/settings-environments/form-localstorage.tsx
packages/platform/src/modules/project/settings/settings-environments/form-sessionstorage.tsx
packages/platform/src/modules/project/settings/settings-environments/index.tsx
packages/platform/src/modules/project/settings/settings-environments/login-script-form.tsx

feat(platform): import and export the environment configuration as JSON format

---

packages/platform-server/src/modules/snapshot/resolver.ts
packages/platform-server/src/modules/snapshot/service.ts
packages/platform/src/modules/group/components/search-projects-select.tsx
packages/platform/src/modules/lab/list/index.tsx
packages/platform/src/modules/lab/list/module.ts
packages/platform/src/modules/lab/operator-comps/lab-filters.tsx
packages/schema/src/graphql/lab/snapshots.gql
packages/schema/src/server-schema.gql

feat(platform-server): search snapshot by title

---

packages/platform/src/modules/project/settings/cards/index.tsx
packages/platform/src/modules/project/settings/settings-pages/index.tsx
packages/platform/src/modules/project/settings/settings-pages/style.tsx
packages/platform/src/modules/project/settings/settings-pages/temp-list.tsx

feat(platform): pages layout

---

packages/bundle-analyzer/src/stats-parser/index.ts
packages/bundle-analyzer/src/stats.ts
packages/bundle-report/src/bundle-content/styled.tsx
packages/bundle-report/src/bundle-content/treeview.tsx
packages/bundle-report/src/bundle-detail/components/colored-size.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/assets-table-row.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/assets-table.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/code.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/import-trace-modal.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/index.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/style.ts
packages/bundle-report/src/static.tsx
packages/platform/src/icons.tsx
packages/plugins/utils/src/build-upload-client.ts
packages/plugins/webpack/src/index.ts
packages/shared/src/bundle/hashcode.ts

feat: module explorer

---

packages/platform-server/src/db/mysql/snapshot.entity.ts
packages/platform-server/src/modules/snapshot/resolver.ts
packages/platform-server/src/modules/snapshot/service.ts
packages/platform/src/modules/lab/list/snapshot-meta.tsx
packages/platform/src/modules/lab/style.ts
packages/schema/src/graphql/lab/snapshot.gql
packages/schema/src/graphql/lab/snapshots.gql
packages/schema/src/graphql/lab/take-snapshot.gql
packages/schema/src/graphql/lab/take-temp-snapshot.gql
packages/schema/src/server-schema.gql

feat(platform-server): add reports status to the snapshot

---

packages/components/src/search-select/index.tsx
packages/platform-server/src/modules/artifact/resolver.ts
packages/platform-server/src/modules/artifact/service.ts
packages/platform/src/modules/components/bundle-property/entrypoint-selector.tsx
packages/platform/src/modules/components/bundle-property/index.ts
packages/platform/src/modules/project/statistics/artifact-size.tsx
packages/platform/src/modules/project/statistics/charts/artifact-size/chart.tsx
packages/platform/src/modules/project/statistics/charts/artifact-size/index.tsx
packages/platform/src/modules/project/statistics/charts/artifact-size/list.tsx
packages/platform/src/modules/project/statistics/charts/artifact-size/module.tsx
packages/platform/src/modules/project/statistics/charts/snapshot-metrics/list.tsx
packages/platform/src/modules/shared/bundle-property.module.ts
packages/schema/src/graphql/project/bundle-report-history.gql
packages/schema/src/graphql/project/entrypoint-history.gql
packages/schema/src/graphql/project/entrypoints.gql
packages/schema/src/server-schema.gql

feat(platform): entrypoint list page

---

packages/platform-server/src/modules/snapshot/snapshot-report/resolver.ts
packages/platform-server/src/modules/snapshot/snapshot-report/service.ts
packages/platform-server/src/modules/snapshot/snapshot-report/types.ts
packages/platform/src/modules/project/statistics/module.ts
packages/platform/src/modules/project/statistics/snapshot-metrics.tsx
packages/schema/src/server-schema.gql

This reverts commit 504d4e59f197ab4909a42359092f516aff093d00.

Revert "fix(platform): fix snapshot metrics selection"

---

packages/bundle-analyzer/src/types.ts
packages/bundle-report/src/bundle-content/index.tsx
packages/bundle-report/src/bundle-content/styled.tsx
packages/bundle-report/src/bundle-content/tooltip.tsx
packages/bundle-report/src/bundle-content/treemap.tsx
packages/bundle-report/src/bundle-detail/components/colored-size.tsx
packages/bundle-report/src/bundle-detail/components/diff.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/assets-table-row.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/assets-table.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/content-modal.tsx
packages/bundle-report/src/bundle-detail/resource-tabs/style.ts
packages/bundle-report/src/bundle-detail/style.ts
packages/platform/src/modules/bundle/bundle-content/index.tsx
packages/platform/src/modules/bundle/bundle-content/module.ts
packages/platform/src/modules/bundle/detail/index.tsx
packages/shared/src/bundle/diff.ts
packages/shared/src/bundle/index.ts
packages/shared/src/bundle/matcher.ts

feat(platform): asset match & module diff

---

packages/bundle-report/src/bundle-detail/components/colored-size.tsx
packages/platform/src/modules/components/version-performance-overview/index.tsx
packages/platform/src/modules/components/version-performance-overview/widgets/artifact-score.tsx
packages/platform/src/modules/project/statistics/index.tsx
packages/platform/src/modules/version-report/index.tsx
packages/platform/src/modules/version-report/types.ts
packages/platform/src/modules/version-report/version-report.module.ts
packages/platform/src/modules/version-report/widgets/audits.tsx
packages/platform/src/modules/version-report/widgets/solution.tsx
packages/platform/src/modules/version-report/widgets/version-selector.tsx
packages/schema/src/graphql/version-report/app-versions.gql
packages/schema/src/graphql/version-report/artifact-by-commit.gql

feat(platform): version report

---

packages/bundle-analyzer/src/stats-parser/index.ts
packages/platform/package.json
packages/platform/src/modules/project/settings/script-editor.tsx
packages/platform/src/modules/project/settings/settings-common-comp.tsx
packages/platform/src/modules/project/settings/settings-environments/login-script-form.tsx
packages/platform/src/modules/project/settings/settings-pages/userflow-script-form.tsx
packages/runner/lab/src/lighthouse/lighthouse-worker.ts
yarn.lock

feat(platform): support script editor
